version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      - NODE_ENV=production
    expose:
      - "3000"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

