version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: node_backend
    expose:
      - "5000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    expose:
      - "80"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

